version: '3.9'

services:

  golang:
    build:
      context: ./
      dockerfile: ./docker/go/Dockerfile
    container_name: golang
    restart: always
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"